-- Deprecated old migration kept as a no-op so the repository stays compatible
-- with environments that still have this file checked out. The active schema
-- now lives in `pricetracker_schema_v2.sql` and companion `*_v2.sql` scripts.
